//Website URL
https://zero4-personal-assignment.onrender.com/api-docs/#/

//Get all contacts
GET https://zero4-personal-assignment.onrender.com/api-docs/#/default/get_contacts_

//Get contact by id
GET https://zero4-personal-assignment.onrender.com/api-docs/#/default/get_contacts__id_


//Create new contact
POST https://zero4-personal-assignment.onrender.com/api-docs/#/default/post_contacts_


//Update contact
PUT https://zero4-personal-assignment.onrender.com/api-docs/#/default/put_contacts__id_


//Delete contact
DELETE https://zero4-personal-assignment.onrender.com/api-docs/#/default/delete_contacts__id_
