//Get all contacts
GET http://localhost:3000/contacts

//Get contact by id
//-----------Needs work----------------------

//Create new contact
POST http://localhost:300/contacts HTTP/1.1
content-type: application/json
{
    "firstName":"Darth",
    "lastName":"Vader",
    "email":"vaderd@empire.com",
    "favoriteColor":"black",
    "birthday":"5/25/1977"
}



//Update contact
PUT http://localhost:3000/contacts/633321f6c90d80dc20cab27e
content-type: application/json
{
    "firstName":"Luke",
    "lastName":"Skywalker",
    "email":"skyluke@rebels.com",
    "favoriteColor":"blue",
    "birthday":"5/25/1977"
}

//Delete contact
DELETE http://localhost:3000/contacts/633321f6c90d80dc20cab27e HTTP/1.1